services:
  postgresdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: insider
    volumes:
      - insider-postgres-data:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - insider
  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  insider-postgres-data:

networks:
  insider:


